# Copyright (c) 2026, ilLumenate Lighting and contributors
# For license information, please see license.txt

"""Text measurement for spec sheet layout, using precomputed HarfBuzz metrics.

``fonts/metrics.json`` is generated by ``tools/spec_sheets/build_font_metrics.py``
from the bundled fonts. Widths match Chromium's shaping for the supported
character set (Latin-1 plus common typographic marks, standard ligatures on).
"""

import json
from functools import cache
from pathlib import Path

FONTS_DIR = Path(__file__).resolve().parent / "fonts"


@cache
def _metrics():
	return json.loads((FONTS_DIR / "metrics.json").read_text(encoding="utf-8"))


def supports(font, text):
	advances = _metrics()[font]["advances"]
	return all(char in advances for char in text)


def text_width(text, font, size, tracking=0):
	"""Advance width in points. ``tracking`` is in 1/1000 em, applied after every character.

	Chromium's ``letter-spacing`` also follows the last character, so this is the
	width a right-aligned (``text-anchor: end``) SVG text occupies.
	"""
	data = _metrics()[font]
	advances, kerning = data["advances"], data["kerning"]
	missing = sorted({char for char in text if char not in advances})
	if missing:
		raise ValueError(f"{font} metrics do not cover {''.join(missing)!r}")
	units = sum(advances[char] for char in text)
	units += sum(kerning.get(text[i : i + 2], 0) for i in range(len(text) - 1))
	return units * size / data["units_per_em"] + tracking * size / 1000 * len(text)
