const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
test('dashboard resume banner dismisses with POST and reveals compact entry',()=>{const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'rendered/finder-banner.html'),'utf8'),{runScripts:'outside-only'}),w=dom.window,requests=[];w.frappe={call:a=>requests.push(a)};w.eval(fs.readFileSync(path.join(__dirname,'../../illumenate_lighting/public/js/product_finder_portal.js'),'utf8'));assert.match(w.document.body.textContent,/Resume \(50% done\)/);w.document.querySelector('[data-finder-dismiss]').click();assert.equal(requests[0].type,'POST');requests[0].callback();assert.equal(w.document.querySelector('#productFinderBanner'),null);assert.equal(w.document.querySelector('#productFinderCompact').hidden,false);dom.window.close();});
test('type chooser features Linear first and preserves schedule draft and Finder',()=>{const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'rendered/finder-chooser.html'),'utf8'),{url:'https://erp.test'});const links=dom.window.document.querySelectorAll('a.card');assert.match(links[0].textContent,/Linear/);for(const link of links){const url=new URL(link.href);assert.equal(url.searchParams.get('schedule'),'S');assert.equal(url.searchParams.get('draft'),'D');assert.equal(url.searchParams.get('finder'),'T');}dom.window.close();});
for (const mode of ['portal','public']) test(mode+' production bundle mounts without Node globals',async()=>{
 const dom=new JSDOM('<div id="ill-configurator-root" data-ill-manual-mount></div>',{runScripts:'outside-only',url:'https://erp.test'}),w=dom.window;
 w.IllConfigurator={existing:true};w.eval(fs.readFileSync(path.join(__dirname,'../../illumenate_lighting/public/product_finder',mode,'ill-finder.js'),'utf8'));
 const client={getDefinition:async()=>({questions:[{id:'family',type:'family',label:'Product type',required:true,options:[{value:'Linear Fixture',label:'Linear Fixture',featured:true}]}],settings:{},glossary:{}}),start:async()=>({token:'T'}),saveAnswers:async()=>({saved:true}),evaluate:async()=>({options:{}})};
 const mounted=w.IllConfigurator.mount('ill-configurator-root',{mode,client});await new Promise(resolve=>setTimeout(resolve,35));
 assert.equal(w.IllConfigurator.existing,true);assert.match(w.document.body.textContent,/Linear Fixture/);mounted.unmount();dom.window.close();
});
